from pathlib import Path
import json
p=Path(__file__).resolve().parent; bodies=p/'issue-bodies';bodies.mkdir(exist_ok=True)
items=[('01-package-payload','[P1] Preserve the complete PyInstaller directory in assembled releases',
'''`release.spec:40` creates an executable with excluded binaries and `release.spec:66` collects its runtime and data files into a directory. The spec sets `contents_directory="."` at `release.spec:57`. But `src/counter_risk/build/release.py:268` copies only the executable at line 284; `assemble_release` registers only that path at line 374. A lead-seat synthetic COLLECT-tree probe copied the executable but omitted both a companion-library sentinel and config. The installed Python runtime cannot rescue a distributed PyInstaller bootloader missing its bundled libraries. This is a verified assembly omission; a real Windows execution remains a required gate, not a claimed local result.''',
'Preserve runtime dependencies and config/templates of the existing one-directory build through assembly and exercise the assembled output.',
['In `src/counter_risk/build/release.py`, preserve the full output tree selected by `release.spec` when assembling the executable and include copied files in the release manifest.', 'Extend `tests/test_release_bundle.py` with a fake COLLECT tree containing a companion library and nested config; assert these survive release assembly.', 'Extend `.github/workflows/release.yml` to run the assembled executable from an unrelated working directory before upload, with a fixture or headless smoke that verifies actual output artifacts.'],
['`python -m pytest tests/test_release_bundle.py -q` passes with a new payload-preservation regression that asserts library and data-file contents, not only executable existence.', 'Deliberate-break gate: temporarily restore the single-file `shutil.copy2` behavior in `src/counter_risk/build/release.py`; the new payload-preservation test must fail for missing companions; revert the break and rerun.', 'The Windows release smoke runs the assembled binary without a repository checkout or Python PATH dependency, returns success, and produces a schema-valid manifest from synthetic fixtures. Archive captured logs with the release build.'],
'Related closed issue #78 introduced packaging, but the concrete full-tree preservation gap persists. Do not expand this into changing runtime formats. Modern generic PyInstaller layouts may use an internal folder; this spec explicitly places companions alongside the executable. See https://pyinstaller.org/en/stable/operating-mode.html .'),
('02-gui-release-launcher','[P1] Launch the GUI executable from the assembled bin directory',
'''`src/counter_risk/build/release.py:281` places the release executable in the bin directory and `src/counter_risk/build/release.py:303` tells operators to double-click the GUI launcher. The shipped `run_counter_risk_gui.cmd:19` checks the development dist layout and line 24 checks the release root, then falls through to source/venv/global commands at lines 30–60. No branch checks the assembled bin directory. Static matched controls confirm the CLI launcher generator knows the bin path while the GUI launcher does not. On a machine with only the documented assembled tree, no existing branch reaches the packaged executable. Windows execution was not available locally.''',
'Align GUI launcher lookup with the assembled release layout while preserving source-checkout fallbacks and exit reporting.',
['Add an explicit assembled-bin executable lookup to `run_counter_risk_gui.cmd` before development/global fallbacks, passing the gui subcommand and preserving failure logs.', 'Extend `tests/test_windows_gui_launcher.py` to cover the assembled-bin branch and retain the source and dist branches.', 'Add a Windows execution gate in `.github/workflows/release.yml` that exercises the launcher selection with a controlled executable or command recorder in the assembled layout.'],
['`python -m pytest tests/test_windows_gui_launcher.py -q` passes, including a regression requiring the bin branch before fallback lookup.', 'A Windows smoke with only the assembled-bin command recorder available captures exactly one invocation with the gui argument; a nonzero controlled child result is reported as failure.', 'Deliberate-break gate: remove the new bin branch in `run_counter_risk_gui.cmd`; the named launcher test and Windows command-recorder smoke must fail; restore the branch.'],
'Independent from payload preservation: a complete runnable binary still needs a launcher branch that selects it. Existing closed packaging issues address the CLI launcher, not this missing GUI path.'),
('03-hhi-doc-reference','[P3] Correct the dated HHI threshold attribution in operator guidance',
'''`docs/concentration_metrics.md:77` attributes the 0.18/0.25 concentration labels to DOJ conventions without a date. The current official DOJ HHI explainer describes a market above 1,800 as highly concentrated under the 2023 Merger Guidelines, so the 2,500 attribution is dated and the text mixes regimes. The document already calls these orientation heuristics, not policy limits. Preserve that distinction: this is a documentation correction, not a request to impose antitrust thresholds on counterparty risk.''',
'Correct or remove the external threshold analogy in the concentration guide, preserving the arithmetic scale explanation and configured portfolio limits.',
['Revise `docs/concentration_metrics.md` operator interpretation paragraph to label any historical threshold with its year or replace it with a dated current official reference.', 'Keep `docs/concentration_metrics.md` explicit that merger-market heuristics do not set portfolio counterparty limits; point operators to the existing limit-monitoring guide.'],
['Documentation verification: the changed paragraph links to the official DOJ HHI explainer, identifies the guideline vintage, and does not describe 2,500 as the undated current highly-concentrated threshold.', 'Deliberate-break verification: temporarily restore the old undated 2,500 attribution in `docs/concentration_metrics.md`; the documented source-comparison checklist must fail; restore the correction and record the comparison in the PR.', 'The documented fractional-to-10,000 conversion and actual calculation/configuration behavior remain unchanged.'],
'Official source checked 2026-09-08: https://www.justice.gov/atr/herfindahl-hirschman-index . No policy approval is required to correct a citation; any portfolio threshold change is outside scope.')]
for stem,title,why,scope,tasks,ac,notes in items:
 text=f'# {title}\n\n## Why\n\n{why}\n\n## Scope\n\n{scope}\n\n## Non-Goals\n\nNo unrelated source or upstream-synced workflow changes. Scaffold-only or partial completion does NOT count as done; complete the observable gates below.\n\n## Tasks\n\n'+''.join('- [ ] '+x+'\n' for x in tasks)+'\n## Acceptance Criteria\n\n'+''.join('- [ ] '+x+'\n' for x in ac)+f'\n## Implementation Notes\n\n{notes}\n'
 (bodies/(stem+'.md')).write_text(text)
(p/'field-and-tools.md').write_text('''# Dimensions 2, 5, 6, 7 and 8 — bounded assessment

Baseline: e2a1bacf37503217e00e467aa72198988777afa4. Sources checked 2026-09-08. These are evidence-based engineering options, not portfolio-policy recommendations.

## Public-field comparison (D5)

The app implements historical notional concentration, configured limit checks, and optional linear notional-times-volatility proxies (README.md:14–19; docs/risk_proxy_outputs.md:17–24). BIS counterparty guidance advocates complementary exposure measures and stress analysis. Inference: this reporting toolkit could gain scenario-based concentration comparisons, but its existing inputs cannot establish netting/collateral-adjusted credit exposure or potential future exposure. Those require netting-set and collateral terms plus a model mandate. Do not label the current toolkit noncompliant or represent bank supervisory guidance as a requirement for this owner.
Source: https://www.bis.org/committees/bcbs/basel-consolidated-guidelines/module/cri/40

The operator HHI guide mixes threshold vintages. A small documentation body is staged, explicitly preserving policy neutrality. Source: https://www.justice.gov/atr/herfindahl-hirschman-index

## Reuse and adjacent opportunities (D2/D6)

AST equality found four duplicate function-body groups (duplicates.json): three demo helpers are duplicated between demo_artifact and web_demo; table-row adapters match in compute/limits and compute/rollups. Duplication alone is not a defect. The demo divergence is already tracked in the August 24 D-1 audit; retain as a known consolidation follow-up, do not open a duplicate. Keep these observations separate from correctness findings.

Short increment: add a scenario delta report over the existing normalized exposures, explicitly marking assumptions and preserving current outputs; first prove split-row/order invariance and conservation before proposing new stress knobs. Roadmap: legally meaningful netting sets, collateral and settlement exposures need input contracts and owner-defined interpretation. No new question is needed for this audit; no financial model or policy choice is made.

## Tool choices (D7)

1. Hypothesis is a candidate for a small dev-only property-test pilot over numeric aggregation: permutation invariance, split/merge conservation, rejected NaN/infinity, and monotonic limit response. Official strategies support targeted finite/non-finite floats. Benefit: catches sibling variations of yesterday's bugs. Cost: generator design and shrinker runtime; deterministic bounded profiles should run in PRs. First compare yield against targeted parametrized tests; do not introduce it solely to raise coverage.
Source: https://hypothesis.readthedocs.io/en/latest/reference/strategies.html
2. Keep openpyxl for workbook manipulation but do not treat a successful save as formula recalculation: its documentation says formulas are not evaluated. Test a representative saved workbook through the existing Excel COM route when calculation matters; do not add a second spreadsheet engine without a demonstrated gap. No new formula-corruption defect was established in this audit.
Source: https://openpyxl.readthedocs.io/en/stable/simple_formulae.html
3. Keep PyInstaller; fix the assembly boundary and execute the actual assembled bundle. Its documented executable/runtime and platform distinctions explain why a shell-script test double cannot establish Windows portability.
Sources: https://pyinstaller.org/en/stable/operating-mode.html and https://pyinstaller.org/en/stable/runtime-information.html

## Local tooling and automation (D8)

Exact-head main CI 34244935833 passed Ruff, Black, mypy and Python 3.12/3.13. PR Gate excludes release/slow suites and disables format_check; this known August 24 concern is retained, not reported as a new incident. Release E2E runs Linux; the Windows release workflow checks file existence without executing the assembled binary. Packaging/launcher staged bodies include concrete runtime gates.

The shared research queue includes Counter_Risk. Live issue snapshot has one implementation item (#996) plus dependency/metrics trackers; its body narrows work to historical_update workflow test coverage. The open PR snapshot contains one dependency-sync PR (#1013), so these audit drafts do not overlap an active feature branch. No independent Counter_Risk-specific Codex automation TOML was found in the bounded name/content search. This is not an assertion about all external scheduler installations.
''')
