from pathlib import Path
p=Path(__file__).resolve().parent/'issue-bodies'
data=[('04-finite-limit','[P1] Reject infinite exposure limits before evaluation',
'''`src/counter_risk/limits_config.py:23` checks only that the limit is positive. YAML positive infinity therefore passes `load_limits_config`, and `src/counter_risk/compute/limits.py:277` subtracts it and drops the negative result as not breached. The normal pipeline consumes this model at `src/counter_risk/pipeline/run.py:2396`. Lead-seat matched controls loaded real temporary YAML: a 100 exposure against 50 produced one fail-severity breach; the same exposure against YAML infinity was accepted and produced zero. This is an invalid-config acceptance defect; no actual owner policy using infinity was observed. Existing enabled=false already represents a staged limit.''',
'Finite validation of LimitEntry.limit_value for all limit kinds, without changing finite threshold semantics.',
['In `src/counter_risk/limits_config.py`, require finite positive `limit_value` and retain the explicit enabled flag for disabled policy entries.', 'Extend `tests/test_limits_config.py` to reject YAML and direct-model positive infinity, negative infinity and NaN with an actionable validation error.', 'Extend `tests/compute/test_limits.py` to preserve a finite breached-limit control and prove non-finite policy cannot reach evaluation.'],
['`python -m pytest tests/test_limits_config.py tests/compute/test_limits.py -q` passes; the new YAML regression rejects positive infinity before check_limits runs.', 'A finite 50 absolute limit against 100 still produces one breach, while explicitly disabled finite limits retain their existing behavior.', 'Deliberate-break gate: remove finite validation from `LimitEntry` in `src/counter_risk/limits_config.py`; the new positive-infinity YAML test must fail; restore the validator and rerun.'],
'Closed #1004 hardens WorkflowConfig cash bounds, not LimitEntry policy values. This is a distinct consumer with a separately reproduced trigger.'),
('05-repo-cash-duplicate','[P2] Collapse duplicate Repo rows when applying authoritative cash',
'''`src/counter_risk/pipeline/run.py:1107` says Repo-cash upsert must prevent duplicate cash, but line 1120 retains only the first matching record in its index and line 1131 replaces only that row. All originals remain in the returned list. The live historical aggregator at `src/counter_risk/pipeline/run.py:4097` sums every normalized-name row. Lead-seat probes supplied two CIBC Repo records with cash 10 and 20 plus authoritative cash 100: the actual injection and historical aggregator reported 120. A single-row control reported 100. This is conditional on duplicated normalized Repo rows; no prevalence claim is made for current operator workbooks.''',
'The injection-to-historical-Cash seam when applying authoritative cash to existing duplicate Repo records.',
['In `src/counter_risk/pipeline/run.py`, make `_inject_repo_cash_into_cprs_ch` collapse or explicitly reject all normalized duplicate Repo records for each authoritative cash key, preserving unrelated rows and segments.', 'Extend `tests/pipeline/test_run_pipeline.py` with duplicate literal names and normalized aliases, passing the injection output into `_aggregate_cprs_ch_series_totals`.', 'Verify in `tests/pipeline/test_run_pipeline.py` that repeating authoritative cash application is idempotent and preserves unrelated counterparties.'],
['`python -m pytest tests/pipeline/test_run_pipeline.py -q -m "not slow and not release"` passes with a named duplicate-Repo-cash regression: 10 and 20 replaced by authoritative 100 cannot aggregate to 120.', 'The one-row control yields 100, unrelated non-Repo records retain their values, and reapplying the same authoritative mapping does not increase Cash.', 'Deliberate-break gate: restore the first-record-only replacement in `_inject_repo_cash_into_cprs_ch` within `src/counter_risk/pipeline/run.py`; the new duplicate-Repo-cash regression must fail; restore the fix.'],
'Closed #1006 is about non-finite structured-source parsing, not duplicate CPRS-CH output rows. Keep the trigger and severity conditional.'),
('06-current-attribution','[P2] Reconcile split current rows before matching prior attribution',
'''`src/counter_risk/reports/change_attribution.py:215` aggregates prior rows, while its loop at line 224 still matches each ungrouped current row to the same prior balance at line 231. In the actual CSV writer path, `src/counter_risk/pipeline/run.py:2069` infers prior balances and passes them to this report. Lead-seat output probes used a current total of 300 and supplied total NotionalChange of 50: one row emitted change 50 and prior 250; splitting the same total into 100 and 200 with changes 25 each emitted summed change -200 and prior 500, with no pipeline warning. Direct helper controls also reproduced the duplicate prior use. The defect requires split or duplicate current counterparty rows; no claim is made that the bundled fixture has them.''',
'Current and prior aggregation consistency in change attribution, including the generated CSV integration path and supplied deltas.',
['In `src/counter_risk/reports/change_attribution.py`, group current rows consistently with prior lookup keys before matching, retaining deterministic labels and summed supplied deltas with explicit missing-delta semantics.', 'Extend `tests/test_change_attribution_report.py` with split-versus-single controls asserting conserved current notional, prior notional and total change.', 'Extend `tests/pipeline/test_run_pipeline.py` to drive `_write_change_attribution_outputs` and parse its CSV for the single 300/change50 versus split 100/change25 and 200/change25 cases.'],
['`python -m pytest tests/test_change_attribution_report.py tests/pipeline/test_run_pipeline.py -q -m "not slow and not release"` passes with a new split-current-conservation regression.', 'The generated CSV has summed current 300, prior 250 and change 50 for both shapes; splitting or permuting current rows cannot duplicate prior notional.', 'Deliberate-break gate: restore the ungrouped current iteration in `src/counter_risk/reports/change_attribution.py`; the new split-current-conservation test must fail with the duplicated prior; restore aggregation and rerun.'],
'Adjacent to closed #1003, which fixed prior-row overwrite only, and #1001, which groups current rows in futures_delta. This is a distinct remaining current-side report gap. The first lead integration probe used an unsupported delta alias and skipped output; the corrected probe uses the actual NotionalChange field and reproduces the CSV defect.')]
for stem,title,why,scope,tasks,ac,notes in data:
 (p/(stem+'.md')).write_text(f'# {title}\n\n## Why\n\n{why}\n\n## Scope\n\n{scope}\n\n## Non-Goals\n\nNo new financial model, source-format rewrite or upstream workflow change. Scaffold-only or partial completion does NOT count as done; the behavior and test gates must be delivered.\n\n## Tasks\n\n'+''.join('- [ ] '+x+'\n' for x in tasks)+'\n## Acceptance Criteria\n\n'+''.join('- [ ] '+x+'\n' for x in ac)+f'\n## Implementation Notes\n\n{notes}\n')
