from pathlib import Path
import json
out=Path(__file__).resolve().parent; bodies=out/'issue-bodies';bodies.mkdir(exist_ok=True)
items=[
('01','P1','Recompile derived agents for sweep and allocation overrides','engine',
'`pa_core/sweep.py:610` and `pa_core/sleeve_suggestor.py:281` copy convenience fields without rebuilding the compiled agents consumed at `pa_core/agents/registry.py:57`. Compilation lives at `pa_core/config.py:674`. In deterministic probes, theta 0 versus 1 produces identical sweep returns while validated single-run controls differ by 0.268241794563. Two materially different cached sleeve allocations likewise have zero return delta versus 0.795856326022 in controls. This combines N1 and N5 as one shared root cause; closed issue #1915 covered round-trip revalidation, which these consumers bypass.',
['In `pa_core/config.py`, expose or reuse a derived-agent refresh that preserves explicit custom agents and avoids converting already-monthly inputs twice.','In `pa_core/sweep.py` and `pa_core/sleeve_suggestor.py`, refresh derived agents after changing capital/share fields before simulation; preserve the sweep policy allowing over-margin candidate exploration.','Extend `tests/test_sweep_config.py` and `tests/test_sleeve_suggestor.py` with deterministic unequal-allocation controls for cached and uncached paths.'],
'pytest tests/test_sweep_config.py tests/test_sleeve_suggestor.py -q',
'Theta endpoints and distinct capital candidates produce the corresponding validated-control metrics, and explicit custom-agent configurations retain their documented behavior.',
'Bypass the derived-agent refresh using the original model_copy behavior; the new endpoint and candidate tests must fail; revert the deliberate break.',
'numeric-lead-recheck.out'),
('02','P1','Apply configured fee schedules to parameter sweeps','engine',
'`pa_core/sweep.py:715` invokes simulate_agents without fee_schedule, while `pa_core/facade.py:483` supplies it for single runs. With a 10% InternalPA sleeve and 120 annual management bps, sweep annual return drag is exactly zero; the matched single-run drag is 0.001199340220. Closed issue #1904 added the working fee layer; this is its missing sweep connection.',
['Pass `mod_cfg.fee_schedule` at the simulate_agents call in `pa_core/sweep.py`.','Extend `tests/test_fee_layer.py` to compare a one-point sweep and single run with deterministic inputs, nonzero fees, zero fees and an absent schedule.'],
'pytest tests/test_fee_layer.py tests/test_sweep_config.py -q',
'The one-point sweep fee drag matches single-run economics and the absent/zero schedule remains a no-op.',
'Remove fee_schedule from the sweep call; the new net-versus-gross test must fail; revert.',
'numeric-lead-recheck.out'),
('03','P1','Scale InternalPA financing by sleeve contribution share','engine',
'`pa_core/agents/internal_pa.py:24` subtracts the full financing rate after scaling alpha. Its docstring at line 18 assigns later scaling to contribution machinery, but `pa_core/portfolio/core.py:34` says inputs are already scaled and line 44 only sums them. With zero alpha and a 1% monthly financing rate, both a 10% sleeve and a 100% sleeve contribute -1%; the partial sleeve should contribute -0.1% under that contract. Related closed #1849 introduced this financing path.',
['In `pa_core/agents/internal_pa.py`, apply the sleeve contribution weight to financing consistently with alpha; align the docstring with the actual scaling location.','Extend `tests/test_agents.py` to cover 10%, 100% and zero shares with positive costs and negative carry, and confirm `simulate_agents` Total sums the corrected contributions.'],
'pytest tests/test_agents.py tests/test_fee_layer.py -q',
'At 1% financing and zero alpha, 10% and 100% shares contribute -0.001 and -0.01 monthly, respectively; negative carry keeps its sign.',
'Restore unscaled financing subtraction; the partial-allocation regression must fail; revert.',
'numeric-lead-recheck.out'),
('04','P2','Preserve common random draws for InternalPA sweep financing','engine',
'`pa_core/sweep.py:602` resets financing generators only when standard financing is not cached. InternalPA draws at `pa_core/sweep.py:703` still advance the original internal RNG even when the other financing series are cached. An ExternalPA theta sweep changes unrelated InternalPA annual returns by -0.000139485503 with 1% InternalPA financing volatility; zero-volatility control delta is exactly zero. Existing common-random-number coverage excludes this stream; related closed #1849 added it.',
['In `pa_core/sweep.py`, cache or reset InternalPA financing draws per combination while retaining deterministic parameter changes and avoiding accidental stream sharing.','Extend `tests/test_sweep_common_random_numbers.py` with duplicate combinations, reordered combinations and nonzero InternalPA financing volatility under a fixed seed.'],
'pytest tests/test_sweep_common_random_numbers.py tests/test_sweep_reproducibility.py -q',
'Duplicate or reordered parameter combinations retain identical InternalPA metrics when that sleeve economics is unchanged; changed financing inputs still change the result.',
'Allow the original internal RNG to advance between duplicate cases; the new equality regression must fail; revert.',
'numeric-lead-recheck.out'),
('05','P1','Calibrate the exported CVaR confidence intervals','engine',
'`pa_core/sim/metrics.py:447` computes standard error only within the selected empirical tail; `pa_core/sim/metrics.py:463` labels the resulting interval as a confidence interval, and `pa_core/sim/metrics.py:638` exports it. The random cutoff uncertainty is not captured by the conditional tail-mean calculation. In 1000 fixed-seed normal trials with 2000 draws each, nominal 95% intervals cover the analytic lower-5% tail mean -2.0627128075074275 only 81.0% of the time. A matched normal-mean interval covers 95.9%. Closed #1917 added this feature; the requested correction concerns calibration, not feature absence.',
['In `pa_core/sim/metrics.py`, implement an estimator of CVaR sampling uncertainty that accounts for empirical-tail selection and independent paths, or withdraw the unsupported CI95 interpretation until such an estimator is available.','Extend `tests/test_metrics.py` with a fixed-seed analytic-normal calibration gate, degenerate tails and dependent-month path fixtures. Document the resampling or asymptotic assumptions beside cvar_confidence_interval.'],
'pytest tests/test_metrics.py -q',
'A retained CI95 method achieves coverage between 0.92 and 0.98 for the specified 1000-trial normal calibration and finite ordered bounds for adequate samples; alternatively unsupported CI95 columns are explicitly deprecated and no longer claimed as 95% intervals.',
'Restore the conditional-tail-only interval and its CI95 export; the calibration or withdrawn-label regression must fail; revert.',
'probe-cvar-result.json'),
('06','P1','Finalize manifest provenance before creating run bundles','data',
'`pa_core/cli.py:1414` and `pa_core/cli.py:2100` create the portable bundle before run-end finalization at `pa_core/cli.py:944`. A real successful 100-path one-point CLI sweep with JSON logging and an index-frequency warning yields two warnings and a cost record in the final manifest, but null warnings and cost in the bundled manifest; timing also differs. This survives the repository lock versions Plotly 6.9.0 and Kaleido 1.3.0. Closed #1834 covered the run envelope; the portable copy remains stale.',
['Reorder or refactor manifest finalization and bundle creation in `pa_core/cli.py` so finalized warnings, cost and timing reach the bundled manifest on every successful completion branch.','Extend `tests/test_run_artifact_bundle.py` with a real CLI run that emits a warning and compares the final standalone and bundled manifest fields; retain bundle hash verification.'],
'pytest tests/test_run_artifact_bundle.py tests/test_run_record_warnings.py -q',
'Bundled and standalone manifests agree on captured warnings, cost and finalized timing after successful CLI completion; bundle.verify returns true.',
'Restore bundle creation before finalization; the new manifest-parity regression must fail; revert.',
'cli-bundle-result.json'),
('07','P2','Keep Run Logs provenance bound to the selected run','ui',
'When selected run-end metadata is absent, `dashboard/pages/7_Run_Logs.py:59` falls back to the working-directory manifest at line 61. A real Streamlit AppTest selects run-selected but displays a manifest identifying WRONG_UNRELATED_RUN. There is no identity check at the display point, line 68. Closed #1901 addressed session handoff; this is a separate incorrect-provenance fallback.',
['In `dashboard/pages/7_Run_Logs.py`, only show a manifest explicitly attributable to the selected run; show the existing missing-manifest guidance when attribution cannot be established.','Extend `tests/test_dashboard_run_logs_page.py` using real AppTest or equivalent runtime observation: selected run without run_end, unrelated root manifest, valid linked manifest, missing linked file, and a malformed run_end.'],
'pytest tests/test_dashboard_run_logs_page.py -q',
'Selecting a run without a valid linked manifest never displays an unrelated root manifest; a valid explicit link still displays its own provenance.',
'Restore the cwd glob fallback; the wrong-run marker test must fail; revert.',
'run-logs-apptest-result.json'),
('08','P2','Ship asset and portfolio samples in installed packages','ui',
'`dashboard/utils.py:146` resolves templates relative to site-packages, while `pyproject.toml:89` includes only data CSV package resources. In an actual non-editable installation, bundled_asset_timeseries_path points to a nonexistent templates file; bundled_sample_index_path exists. The same template resolver feeds the portfolio starter at `dashboard/utils.py:177`. Closed #2026 added checkout samples; the installed layout still lacks their files.',
['Update package resources in `pyproject.toml` and the sample resolvers in `dashboard/utils.py` so asset CSV and portfolio YAML ship and resolve in a wheel install outside the source checkout.','Extend `tests/test_dashboard_sample_data.py` or add a packaging smoke helper wired into the existing package-validation test command to build/install a wheel and open all three samples.'],
'pytest tests/test_dashboard_sample_data.py -q',
'A built non-editable wheel installed into an isolated environment outside the checkout exposes readable asset CSV, portfolio YAML and index CSV without relying on repository-relative templates.',
'Omit the asset and portfolio resources from package data; the named wheel-install smoke must fail; revert.',
'installed-sample-result.json'),
('09','P1','Make the bundled Asset Library sample load with defaults','ui',
'`templates/asset_timeseries_wide_returns.csv:2` begins a 24-observation sample, but `dashboard/pages/1_Asset_Library.py:116` sets minimum observations to 36. Selecting the bundled sample in a clean browser triggers the uncaught importer error at `dashboard/pages/1_Asset_Library.py:204`: insufficient data for FUND_A, FUND_B, SP500_TR. The initial page loads, but the advertised no-upload path fails. This is a residual behavior failure after closed #2026, distinct from the installed-resource omission.',
['Align `templates/asset_timeseries_wide_returns.csv` and the bundled-sample behavior in `dashboard/pages/1_Asset_Library.py` so the supplied fixture meets the retained data-quality minimum without silently weakening validation for uploaded user data.','In `dashboard/pages/1_Asset_Library.py`, present actionable guidance for insufficient-data imports instead of propagating the raw exception.','Extend `tests/test_dashboard_asset_library.py` to run the real sample at the actual default minimum using AppTest, and exercise an insufficient uploaded series.'],
'pytest tests/test_dashboard_asset_library.py tests/test_asset_library_exception_handling.py -q',
'A fresh Asset Library session can select the bundled sample and reach Data loaded successfully with no exception and no manual parameter edits; undersized user uploads receive explicit guidance.',
'Restore the 24-row fixture with an unchanged minimum36; the real-default sample regression must fail; revert.',
'asset-sample-a11y.txt'),
('10','P1','Support Plotly 7 image export or constrain installation','infra',
'`pyproject.toml:119` permits Plotly 7, but `pa_core/viz/export_backend.py:88` passes the removed engine keyword to to_image and line 100 passes it to write_image. A clean dependency solve installed Plotly 7.0.0; a real CLI sweep crashed with TypeError before manifest completion. The repository lock pins Plotly 6.9.0, and the same command succeeds under that pin. `pa_core/reporting/sweep_excel.py:96` skips the affected chart branch in CI, explaining why green CI does not refute this supported-install failure. Plotly documents this removal: https://plotly.com/python/static-image-generation-changes/ . This overturns the delegated environmental-only dismissal.',
['Remove deprecated explicit engine arguments in `pa_core/viz/export_backend.py` with compatibility coverage, or add an explicit temporary supported-version constraint in `pyproject.toml` until migration is delivered.','Extend `tests/test_export_backend.py` to exercise actual supported Plotly signatures and add a real CLI export smoke outside the CI/PYTEST_CURRENT_TEST bypass in `pa_core/reporting/sweep_excel.py`.'],
'pytest tests/test_export_backend.py -q',
'A fresh installation cannot resolve an unsupported Plotly version, or a real PNG and CLI sweep export succeeds with Plotly7; the supported lock-version export still succeeds.',
'Restore engine="kaleido" without a dependency constraint; the real Plotly7 signature/export regression must fail; revert.',
'cli-bundle-proof/cli-plotly7-failure.log'),
]
for num,priority,title,area,why,tasks,gate,accept,breaking,evidence in items:
 body='## Why\n\n'+why+'\n\n## Scope\n\n'+title+'. First-party '+area+' behavior at main 59cb12be9d4b06434d41bc1b71612167ea6d9cfc.\n\n## Non-Goals\n\nNo unrelated refactors, synced workflow changes, new hosted service, or placeholder/scaffold-only implementation. Do not weaken the named regression to make it pass.\n\n## Tasks\n\n'+'\n'.join('- [ ] '+t for t in tasks)+'\n\n## Acceptance Criteria\n\n- [ ] '+accept+'\n- [ ] Run `'+gate+'` with the added regressions and retain output.\n- [ ] Deliberate-break check: '+breaking+'\n\n## Implementation Notes\n\nSeverity '+priority+'. Source citations are relative to this repository. Preserve existing documented semantics outside the correction.\n'
 (bodies/(num+'.md')).write_text(body)
manifest=[{'id':n,'priority':p,'title':t,'labels':['bug',a,'priority: high' if p=='P1' else 'priority: medium'],'body':str(bodies/(n+'.md')),'evidence':e,'status':'staged-research-only'} for n,p,t,a,w,ts,g,ac,br,e in items]
(out/'draft-index.json').write_text(json.dumps(manifest,indent=2))
print('Wrote',len(items),'drafts')
